// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
  "wlecom": "مرحبا بك !",
  "pls": "رجاءً أدخل حسابك هنا ",
  "email": "البريد الالكتروني ",
  "password": "كلمة السر ",
  "signin": "تسجيل الدخول",
  "noacc": "لا تمتلك حساباً ؟ ",
  "signup": " انشاء حساب",
  "creatnewacc": "انشاء حساب جديد",
  "pls2": "رجاءً املأ التالي للتقدم",
  "fname": "الاسم الأول",
  "Lname": "الأسم الأخير",
  "phone": "رقم الجوال",
  "address": "الموقع",
  "conpass": "تأكيد كلمة السر",
  "acc": "تمتلك حساب ؟ ",
  "carttitle": "حقيبتك",
  "total": "الإجمالي :",
  "ordernow": "إطلب الآن !",
  "editeproducttitle": "تعديل المنتج ",
  "title": "الاسم",
  "price": "السعر",
  "condition": "الحالة",
  "description": "الوصف ",
  "categorytitle": "تصنيف منتجك :",
  "categoryhint": "اختر تصنيفاً من فضلك",
  "noimage": "لم يتم التقاط صورة",
  "takeimage": "التقاط صورة",
  "urordertitle": "طلباتك",
  "itemtwiceadded": "لا يمكن إضافة المنتج مرتين ",
  "itemaddedtocart": "تم إضافة المنتج إلى السلة !",
  "ok": "حسناً",
  "undo": "تراجع",
  "overview": "نظرة عامة : ",
  "createdby": "صاحب المنتج : ",
  "comments": "التعليقات :",
  "urcomment": " تعليقك :",
  "editecomment": "تعديل التعليق ؟ ",
  "deletecomment": "حذف التعليق ؟ ",
  "addcomment": "أضف تعليقك : ",
  "home": "الرئيسية",
  "favs": "المفضلة",
  "search": "البحث",
  "sittings": "الإعدادات",
  "newproductstitle": "أحدث المنتجات في المتجر ",
  "urfavs": "منتجاتك المفضلة : ",
  "avalibenow": "المنتجات المتوفرة :",
  "itemssold": "المنتجات المباعة :",
  "ratingnow": " التقييم الحالي : ",
  "reviews": "التقييمات : ",
  "urreview": "تقييمك : ",
  "editereview": "تعديل التقييم ؟ ",
  "deletereview": "حذف التقييم ؟",
  "addreview": "إضافة تقييمك",
  "urprofiletilte": "حسابك الشخصي",
  "profnav": "الحساب",
  "revnav": "التقييمات",
  "itemsinstore": "المنتجات في المتجر",
  "confirmchanges": "تأكيد التغييرات ؟",
  "searchtitle": "ابحث عن ما تريد : ",
  "noresult": "لم يتم إيجاد منتجات :( ",
  "sittingtitle": "الإعدادات",
  "common": "عام",
  "environment": "البيئة",
  "signout": "تسجيل الخروج",
  "personalization": "التخصيص ",
  "language": "اللغة",
  "theme": "الوضع الليلي",
  "misc": "Misc",
  "terms": "بنود الخدمة والأمان ",
  "source": "Open Source and Licences",
  "loading": "يتم التحميل ...",
  "urproducts": "منتجاتك",
  "drawertitle": "إلى أين ؟",
  "drawershope": "المتجر",
  "drawerOrders": "الطلبات",
  "drawerManageProducts": "إدارة منتجاتك ",
  "drawerProfile": "الحساب الشخصي",
  "drawerlogout": "تسجيل الخروج",
  "commenthint": "أدخل تعليقك ",
  "addrevhere": "أدخل تقييمك هنا ",
  "addcomhere": "أدخل تعليقك هنا ",
  "revhint": "أكتب شيئا مفيداً ",
  "revratingadd": "أضف التقييم : ",
  "accepted": "مقبول : ",
  "pending": "قيد التدقيق : ",
  "rejected": "مرفوض : ",
  "cantaddyourown": "لا يمكنك إضافة منتجاتك !",
  "clothes": "الملابس",
  "tools": "الأدوات",
  "kitchenUtilities": " أغراض المطبخ",
  "furniture": "الأثاث",
  "searchbytitle": "البحث عبر الاسم",
  "searchbyprice": "البحث عبر السعر",
  "tilterror": "الرجاء ادخال اسم للمنتج ",
  "priceerror1": "الرجاء ادخال سعر ",
  "priceerror2": "الرجاء ادخال رقم مقبول",
  "priceerror3": "الرجاء ادخال رقم اكبر من الصفر ",
  "conerror": "الرجاء ادخال حالة للمنتج ",
  "descerror1": "الرجاء ادخال وصف للمنتج ",
  "descerror2": "الرجاء ادخال وصف اطول للمنتج ",
  "anerroraccured": "حدث خطأ ما ",
  "sure": "هل انت متأكد ! ",
  "deletconf": " هل تريد حذف هذا المنتج من حقيبتك ؟",
  "yes": "نعم",
  "no": "لا"
};
static const Map<String,dynamic> en = {
  "wlecom": "Welcome Back!",
  "pls": "Please sign in to your account",
  "email": "Email Address",
  "password": "Password",
  "signin": "Sign in",
  "noacc": "Don\\'t have an account? ",
  "signup": " Sign Up",
  "creatnewacc": "Create new account",
  "pls2": "Please fill in the form to continue",
  "fname": "First Name",
  "Lname": "Last Name",
  "phone": "Phone Number",
  "address": "Location",
  "conpass": "Confirm Password",
  "acc": "Have an account? ",
  "carttitle": "Your Cart",
  "total": "Total : ",
  "ordernow": "Order Now !",
  "editeproducttitle": " Edite Product ",
  "title": "Title ",
  "price": "Price ",
  "condition": "Condition",
  "description": "Description ",
  "categorytitle": "Your items Category : ",
  "categoryhint": " Please Pick a Category ",
  "noimage": "No Image Taken",
  "takeimage": "Take An Image",
  "urordertitle": "Your Orders",
  "itemtwiceadded": "Cant Add Item Twice ! ",
  "itemaddedtocart": "Added Item To The Cart ! ",
  "ok": "Ok",
  "undo": "Undo",
  "overview": "Over View : ",
  "createdby": "Created By : ",
  "comments": " Comments : ",
  "urcomment": " Your Comment : ",
  "editecomment": "Edit Comment ? ",
  "deletecomment": "Delete Comment ? ",
  "addcomment": "Add Your Comment  : ",
  "home": "Home",
  "favs": "Favorits",
  "search": "Search",
  "sittings": "Settings",
  "newproductstitle": "New Products Preview : ",
  "urfavs": "Your Favorites : ",
  "avalibenow": "Available Now : ",
  "itemssold": " Items Sold   : ",
  "ratingnow": "Current  Rating  : ",
  "reviews": "  Reviews : ",
  "urreview": " Your Review : ",
  "editereview": "Edit Review ? ",
  "deletereview": "Delete Review ? ",
  "addreview": "Add Review ",
  "urprofiletilte": "Your Profile",
  "profnav": "Profile",
  "revnav": "Reviews",
  "itemsinstore": "Items In Store ",
  "confirmchanges": "Confirm Changes ?",
  "searchtitle": "Search For Your Needs : ",
  "noresult": "no results found :( ",
  "sittingtitle": "Settings",
  "common": "Common",
  "environment": "Environment",
  "signout": "Sign Out",
  "personalization": "Personalization",
  "language": "Language",
  "theme": "Dark Theme",
  "misc": "Misc",
  "terms": "Terms of Service",
  "source": "Open Source and Licences",
  "loading": "Loading...",
  "urproducts": "Your Products",
  "drawertitle": "Where To ? ",
  "drawershope": "Shop",
  "drawerOrders": "Orders",
  "drawerManageProducts": "Manage Products",
  "drawerProfile": "Profile",
  "drawerlogout": "LOG OUT",
  "commenthint": "Input Your Comment here",
  "addrevhere": "Add Your Review Here : ",
  "addcomhere": "Add Your Comment Here : ",
  "revhint": "Input Your Review here",
  "revratingadd": "Add Your Rating : ",
  "accepted": "Accepted : ",
  "pending": "Pending : ",
  "rejected": "Rejected : ",
  "cantaddyourown": "Cant Add Your Own Item !",
  "clothes": "Clothes",
  "tools": "Tools",
  "kitchenUtilities": " Kitchen Utilities",
  "furniture": "Furniture",
  "searchbytitle": "Search By Title",
  "searchbyprice": "Search By Price",
  "tilterror": "Please Enter A Title.",
  "priceerror1": "Please Enter A Price.",
  "priceerror2": "Pleas Enter A valid Number.",
  "priceerror3": "Pleas Enter A Number Greater Than Zero .",
  "conerror": "Please Enter A Condition.",
  "descerror1": "Please Enter A Description.",
  "descerror2": "Please Enter A Longer Description.",
  "anerroraccured": "An Error Occurred",
  "sure": "Are You Sure ?",
  "deletconf": "Do you want to delete this item from cart ? ",
  "yes": "YES",
  "no": "NO"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en};
}
